# Generated by Django 5.0 on 2024-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('task_type', models.CharField(choices=[('code_generation', 'Code Generation'), ('code_explanation', 'Code Explanation'), ('error_fixing', 'Error Fixing'), ('conversation', 'Conversation')], default='conversation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_chatmessage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_chatmes_created_d12f96_idx'), models.Index(fields=['task_type'], name='api_chatmes_task_ty_ae6f2e_idx')],
            },
        ),
    ]
